config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  resources :users, except: [:update] do
    member do
      get :followings
      get :followers
    end
  end

  patch "/users/:id/edit", to: "users#update"
  put "/users/:id/edit", to: "users#update"

  resources :relationships, only: [:create, :destroy]

  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :password_resets, only: [:new, :create, :edit, :update]
  post "/password_resets/new", to: "password_resets#create"
  post "/password_resets/:id/edit", to: "password_resets#update"
  put "/password_resets/:id/edit", to: "password_resets#update"
  patch "/password_resets/:id/edit", to: "password_resets#update"

  resources :microposts, only: [:destroy]
  post "/", to: "microposts#create"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    if @user = User.find_by(email: params[:password_reset][:email].downcase)
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render "new"
    end

  end

  def edit
  end

  def update

    case
    when params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render "edit"
    when @user.update_attributes(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render "edit"
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      redirect_to root_url unless (@user&.activated? && @user.authenticated?(:reset, params[:id]))
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: edit_password_reset_path(params[:id]), local: true) do |f| %>
      <%= render "shared/error_messages", obj: f.object %>
      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, for: "reset_password" %>
      <%= f.password_field :password, id:"reset_password", class: "form-control"%>

      <%= f.label :password_confirmation, for: "reset_password_confirmation" %>
      <%= f.password_field :password_confirmation, id: "reset_password_confirmation", class: "form-control" %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>

  </div>

</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(scope: :password_reset, url: new_password_reset_path, local: true) do |f| %>
      <%= f.label :email, for: "email_to_reset" %>
      <%= f.email_field :email, id: "email_to_reset", class: "form-control" %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>