config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  resources :users, except: [:update] do
    member do
      get :followings
      get :followers
    end
  end

  patch "/users/:id/edit", to: "users#update"
  put "/users/:id/edit", to: "users#update"

  resources :relationships, only: [:create, :destroy]

  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :password_resets, only: [:new, :create, :edit, :update]
  post "/password_resets/new", to: "password_resets#create"
  post "/password_resets/:id/edit", to: "password_resets#update"
  put "/password_resets/:id/edit", to: "password_resets#update"
  patch "/password_resets/:id/edit", to: "password_resets#update"

  resources :microposts, only: [:destroy]
  post "/", to: "microposts#create"
end

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(obj.errors.count, "error")  %>
    </div>
    <ul class="errors_ul">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items&.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, url: root_path , local: true) do |f| %>
  <%= render "shared/error_messages", obj: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, id: "micropost_picture", accept: "image/jpeg, image/gif, image/png" %>
  </span>

  <script type="text/javascript">
    $("#micropost_picture").bind("change", function(){
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5){
        alert("Maximum file size is 5MB. Please choose a smaller file.");
      }
    });
  </script>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= followings_user_path(@user) %>">
    <strong id="followings", class="stat">
      <%= @user.followings.count %>
    </strong>
    followings
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers", class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>